import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "First App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <header style={{ backgroundColor: "cyan", padding: "1rem" }}>Header</header>
        {children}
        <footer style={{ backgroundColor: "cyan", padding: "1rem" }}>Footer</footer>
      </body>
    </html>
  );
}
